//CREATE USERS
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "roihan",
    "email": "roihan@gmail.com",
    "password": "test123",
    "confPassword": "test123",
    "role": "user"
}

###
//LOGIN ADMIN
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "admin1@gmail.com",
    "password": "test123"
}

###
//LOGIN USER
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "roihan@gmail.com",
    "password": "test123"
}


###
//GET USER LOGIN
GET  http://localhost:5000/me

###
//LOGOUT
DELETE   http://localhost:5000/logout

###
//GET ALL USERS
GET  http://localhost:5000/users


###
//GET SINGLE USERS
GET  http://localhost:5000/users/186d14c4-9d81-46d4-8878-701f1b070707

###
//UPDATE SINGLE USERS
PATCH  http://localhost:5000/users/d52a5525-1d98-4015-977e-38a421694fdc
Content-Type: application/json

{
    "name": "test update",
    "email": "test@gmail.com",
    "password": "",
    "confPassword": "",
    "role": "user"
}

###
//DELETE SINGLE USERS
DELETE   http://localhost:5000/users/d52a5525-1d98-4015-977e-38a421694fdc

### 
//GET ALL PRODUCTS
GET  http://localhost:5000/products

### 
//GET SINGLE PRODUCTS
GET  http://localhost:5000/products/0453d8fd-8069-4b07-8d79-b6e59172b468

###
//CREATE PRODUCTS
POST http://localhost:5000/products
Content-Type: application/json

{
    "name": "product6",
    "price": 800
}


###
//UPDATE PRODUCTS
PATCH  http://localhost:5000/products/b3267bd2-27e8-483d-a2b4-5fcb3c95a136
Content-Type: application/json

{
    "name": "product 6 updated",
    "price": 1000
}

###
//DELETE PRODUCTS
DELETE   http://localhost:5000/products/b3267bd2-27e8-483d-a2b4-5fcb3c95a136
Content-Type: application/json


